imports:
  - "partials/site.hyperbricks.yaml"

patterns_index:
  - inherit: "pattern_site_page"
  - route: index
  - template_10:
      - type: template
      - template:
          file: patterns/index.html
