imports:
  - "partials/site.hyperbricks.yaml"

patterns_index:
  - inherit: "pattern_site_page"
  - route: index
  - content:
      - type: template
      - template:
          file: patterns/index.html
      - values:
          spaces_editor_url: {config: {path: hyperbricks.development.frontend_editing.spaces.route, default: /__hyperbricks/spaces}}
