"""EPUB regressions: reader-visible markup, diagrams, navigation and packaging."""
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch
import xml.etree.ElementTree as ET
from zipfile import ZipFile, ZIP_STORED

import build_epub_compilations as epub


class EpubTests(unittest.TestCase):
    def test_markup_examples_tables_and_diagrams(self):
        markdown = '''<!-- Generated by internal tool -->
# HyperBricks Documentation Compilation v1.2.5-beta
## Contents
### Start
- [Getting started](#chapter) — `docs/INTRODUCTION.md`

<a id="chapter"></a>

## Introduction

<a id="section"></a>

### Section
[Return](#chapter)

```html
<a id="example"></a>
<!-- Keep this code example -->
```

| A | B |
| - | - |
| 1 | 2 |

```mermaid
graph TD; A-->B
```
'''
        with tempfile.TemporaryDirectory() as directory, patch('build_compilations.render_mermaid', return_value=b'png-fixture') as renderer:
            output = Path(directory) / 'book.epub'
            epub.epub_for(Path('Documentation.md'), output, markdown=markdown)
            with ZipFile(output) as book:
                self.assertEqual(book.infolist()[0].filename, 'mimetype')
                self.assertEqual(book.infolist()[0].compress_type, ZIP_STORED)
                self.assertEqual(book.read('mimetype'), b'application/epub+zip')
                package = book.read('OEBPS/package.opf')
                self.assertIn(b'<dc:title>HyperBricks Documentation Compilation v1.2.5-beta</dc:title>', package)
                self.assertNotIn(b'Handbook', package)
                root = ET.fromstring(book.read('OEBPS/content.xhtml'))
                visible = ''.join(root.itertext())
                self.assertNotIn('Generated by internal tool', visible)
                self.assertNotIn('<a id="chapter">', visible)
                self.assertIn('<a id="example"></a>', visible)
                self.assertIn('<!-- Keep this code example -->', visible)
                self.assertNotIn('graph TD', visible)
                ns = {'h': 'http://www.w3.org/1999/xhtml'}
                self.assertIsNotNone(root.find('.//h:table', ns))
                ids = {element.get('id') for element in root.iter() if element.get('id')}
                self.assertIn('chapter', ids)
                nav = ET.fromstring(book.read('OEBPS/nav.xhtml'))
                links = nav.findall('.//h:a', ns)
                self.assertEqual(len(links), 4)
                self.assertIn('Start', [link.text for link in links])
                self.assertIn('Getting started', [link.text for link in links])
                self.assertNotIn('Introduction', [link.text for link in links])
                for link in links:
                    self.assertIn(link.get('href').split('#')[1], ids)
                for img in root.findall('.//h:img', ns):
                    self.assertEqual(book.read('OEBPS/' + img.get('src')), b'png-fixture')
                renderer.assert_called_once()

    def test_dark_theme_and_reflow(self):
        self.assertIn('prefers-color-scheme: dark', epub.STYLES)
        self.assertIn('white-space: pre-wrap', epub.STYLES)
        self.assertIn('hyphens: none', epub.STYLES)
        self.assertIn('Arial, Helvetica, sans-serif', epub.STYLES)

    def test_raw_html_is_not_executed(self):
        body, _, _ = epub.render_content('<script>alert(1)</script>\n', None)
        self.assertNotIn('<script>', body)
        self.assertIn('&lt;script&gt;', body)


if __name__ == '__main__':
    unittest.main()
