services:
  hyperbricks-deploy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        TAILWIND_VERSION: "4.1.10"
    ports:
      - "9090:9090"
      - "8080-8100:8080-8100"
    environment:
      HB_DEPLOY_SECRET: "change-me"
    volumes:
      - ./data/deploy:/opt/hyperbricks/deploy
      - ./deploy.hyperbricks.yaml:/opt/hyperbricks/deploy.hyperbricks.yaml:ro
    restart: unless-stopped
