name: CI for Current Branch (Go)
permissions:
  contents: write
on:
  push:
    branches:
      - '*'   # Triggers on any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Build and start services
        run: docker compose -f ./test/dedicated/docker/docker-compose.yml up -d --build

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..20}; do
            if docker exec postgres_db pg_isready -U postgres; then
              echo "Postgres is ready!"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 3
          done

      - name: Run all tests
        run: ./scripts/run_all_tests.sh
        env:
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Tear down containers
        if: always()
        run: docker compose -f ./test/dedicated/docker/docker-compose.yml down -v
